name: Build master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Java Setup
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          java-version: '8'
          distribution: 'temurin'

      - name: Install
        run: |
          mvn -B clean install
